CREATE TABLE NOTICE_BOARD
   (	MB_ID VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	NOTICE_BOARD_TITLE VARCHAR2(200 BYTE), 
	NOTICE_BOARD_CONTENT VARCHAR2(500 BYTE), 
	NOTICE_BOARD_DATE DATE, 
	NOTICE_BOARD_PICTURE VARCHAR2(200 BYTE), 
	NOTICE_BOARD_READCNT NUMBER, 
	NOTICE_BOARD_NO NUMBER, 
	 CONSTRAINT NOTICE_BOARD_FK1 FOREIGN KEY (MB_ID)
	  REFERENCES MEMBER (MB_ID) ENABLE
   )
   
   CREATE SEQUENCE  NOTICE_BOARD_SEQ  
   MINVALUE 1 
   MAXVALUE 99999999999 
   INCREMENT BY 1 
   START WITH 21 
   CACHE 20 NOORDER  
   NOCYCLE ;