--테이블

--영화정보
CREATE TABLE MOVIE_INFO(
  MV_INFO_SEQ   NUMBER  PRIMARY KEY,
  MV_TITLE  VARCHAR2(100),
  MV_SUB_TITLE  VARCHAR2(200),
  MV_PUB_DATE  VARCHAR2(50),
  MV_DIRECTOR  VARCHAR2(100),
  MV_ACTOR  VARCHAR2(1000),
  MV_USER_RATING  VARCHAR2(50),
  MV_LINK VARCHAR2(100),
  MV_IMAGE VARCHAR2(2000)
  );
  
  DROP TABLE MOVIE_VISUAL_ITEMS;
  
  --영화 사진 / 영상 아이템
  CREATE TABLE MOVIE_VISUAL_ITEMS(
  MV_VISUAL_SEQ   NUMBER,
  MV_INFO_SEQ  NUMBER  REFERENCES MOVIE_INFO(MV_INFO_SEQ) ON DELETE CASCADE,
  MV_TITLE VARCHAR2(100),
  MV_STILLCUT  VARCHAR2(1000),
  MV_TRAILER  VARCHAR2(1000)
  );
  
  --한줄평
  CREATE TABLE MOVIE_REVIEW(
  MV_RV_SEQ  NUMBER,
  USER_ID  VARCHAR2(100),
  MV_RV_TITLE  VARCHAR2(1000) ,
  MV_RV_CONTENTS  VARCHAR2(4000),
  MV_RV_RATING  NUMBER
  );
  
  --시퀀스

--영화 정보
  DROP SEQUENCE MOVIE_INFO_SEQ;
  CREATE SEQUENCE MOVIE_INFO_SEQ;
  
  --영화 사진 / 영상 아이템
    DROP SEQUENCE MOVIE_VISUAL_ITEMS_SEQ;
 CREATE SEQUENCE MOVIE_VISUAL_ITEMS_SEQ;
 
 --한줄평
 CREATE SEQUENCE MOVIE_REVIEW_SEQ;
  