DROP TABLE MEMBER;
CREATE TABLE MEMBER(
	MB_ID          VARCHAR2(30),
	MB_PASSWD      VARCHAR2(30) NOT NULL,
	MB_NAME        VARCHAR2(30) NOT NULL,
	MB_MAIL        VARCHAR2(30),
	MB_MAILDOMAIN  VARCHAR2(20),
	MB_PHONE       VARCHAR2(15) NOT NULL,
	PRIMARY KEY(ID)
);

INSERT INTO member values('kjm', 'qwe123', '김종민', 'kjm', 'google.com', '01012341234');

SELECT id FROM member WHERE id='km' AND passwd='123qwe';

SELECT * FROM MEMBER;