DROP TABLE CINEMA_RESERVE;
  CREATE TABLE CINEMA_RESERVE
   (	CINEMA_NAME VARCHAR2(200 BYTE), 
	CINEMA_SECTION VARCHAR2(50 BYTE), 
	CINEMA_MOVIE VARCHAR2(50 BYTE), 
	CINEMA_MOVIE_TIME VARCHAR2(30 BYTE), 
	CINEMA_MOVIE_SEAT VARCHAR2(20 BYTE), 
	MB_ID VARCHAR2(30 BYTE), 
	CINEMA_RESERVE_NO VARCHAR2(30 BYTE)
   );

Insert into ARMY.CINEMA_RESERVE (CINEMA_NAME,CINEMA_SECTION,CINEMA_MOVIE,CINEMA_MOVIE_TIME,CINEMA_MOVIE_SEAT,MB_ID,CINEMA_RESERVE_NO) values ('kst 목동','임시 상영관','어벤져스','11:50','1_11','worua99','2018041218.1_98');
Insert into ARMY.CINEMA_RESERVE (CINEMA_NAME,CINEMA_SECTION,CINEMA_MOVIE,CINEMA_MOVIE_TIME,CINEMA_MOVIE_SEAT,MB_ID,CINEMA_RESERVE_NO) values ('kst 목동','임시 상영관','어벤져스','11:50','1_12','worua99','2018041218.1_98');
Insert into ARMY.CINEMA_RESERVE (CINEMA_NAME,CINEMA_SECTION,CINEMA_MOVIE,CINEMA_MOVIE_TIME,CINEMA_MOVIE_SEAT,MB_ID,CINEMA_RESERVE_NO) values ('kst 목동','임시 상영관','어벤져스','11:50','2_9','worua99','2018041218.1_98');
Insert into ARMY.CINEMA_RESERVE (CINEMA_NAME,CINEMA_SECTION,CINEMA_MOVIE,CINEMA_MOVIE_TIME,CINEMA_MOVIE_SEAT,MB_ID,CINEMA_RESERVE_NO) values ('kst 목동','임시 상영관','어벤져스','11:50','2_10','worua99','2018041218.1_98');
Insert into ARMY.CINEMA_RESERVE (CINEMA_NAME,CINEMA_SECTION,CINEMA_MOVIE,CINEMA_MOVIE_TIME,CINEMA_MOVIE_SEAT,MB_ID,CINEMA_RESERVE_NO) values ('kst 목동','임시 상영관','어벤져스','11:50','2_11','worua99','2018041218.1_98');
Insert into ARMY.CINEMA_RESERVE (CINEMA_NAME,CINEMA_SECTION,CINEMA_MOVIE,CINEMA_MOVIE_TIME,CINEMA_MOVIE_SEAT,MB_ID,CINEMA_RESERVE_NO) values ('kst 목동','임시 상영관','어벤져스','11:50','2_12','worua99','2018041218.1_98');
Insert into ARMY.CINEMA_RESERVE (CINEMA_NAME,CINEMA_SECTION,CINEMA_MOVIE,CINEMA_MOVIE_TIME,CINEMA_MOVIE_SEAT,MB_ID,CINEMA_RESERVE_NO) values ('cgv 강남','임시 상영관','Dead pool','11:50','1_4','worua99','2018041221.1_48');
Insert into ARMY.CINEMA_RESERVE (CINEMA_NAME,CINEMA_SECTION,CINEMA_MOVIE,CINEMA_MOVIE_TIME,CINEMA_MOVIE_SEAT,MB_ID,CINEMA_RESERVE_NO) values ('cgv 강남','임시 상영관','Dead pool','11:50','1_5','worua99','2018041221.1_48');
Insert into ARMY.CINEMA_RESERVE (CINEMA_NAME,CINEMA_SECTION,CINEMA_MOVIE,CINEMA_MOVIE_TIME,CINEMA_MOVIE_SEAT,MB_ID,CINEMA_RESERVE_NO) values ('cgv 강남','임시 상영관','Dead pool','11:50','1_6','worua99','2018041221.1_48');
Insert into ARMY.CINEMA_RESERVE (CINEMA_NAME,CINEMA_SECTION,CINEMA_MOVIE,CINEMA_MOVIE_TIME,CINEMA_MOVIE_SEAT,MB_ID,CINEMA_RESERVE_NO) values ('cgv 강남','임시 상영관','Dead pool','11:50','1_7','worua99','2018041221.1_48');
Insert into ARMY.CINEMA_RESERVE (CINEMA_NAME,CINEMA_SECTION,CINEMA_MOVIE,CINEMA_MOVIE_TIME,CINEMA_MOVIE_SEAT,MB_ID,CINEMA_RESERVE_NO) values ('cgv 강남','임시 상영관','Dead pool','11:50','3_2','worua99','2018041221.1_48');
Insert into ARMY.CINEMA_RESERVE (CINEMA_NAME,CINEMA_SECTION,CINEMA_MOVIE,CINEMA_MOVIE_TIME,CINEMA_MOVIE_SEAT,MB_ID,CINEMA_RESERVE_NO) values ('cgv 강남','임시 상영관','Dead pool','11:50','3_3','worua99','2018041221.1_48');
Insert into ARMY.CINEMA_RESERVE (CINEMA_NAME,CINEMA_SECTION,CINEMA_MOVIE,CINEMA_MOVIE_TIME,CINEMA_MOVIE_SEAT,MB_ID,CINEMA_RESERVE_NO) values ('cgv 강남','임시 상영관','Dead pool','11:50','4_4','worua99','2018041221.1_48');
Insert into ARMY.CINEMA_RESERVE (CINEMA_NAME,CINEMA_SECTION,CINEMA_MOVIE,CINEMA_MOVIE_TIME,CINEMA_MOVIE_SEAT,MB_ID,CINEMA_RESERVE_NO) values ('cgv 강남','임시 상영관','Dead pool','11:50','5_3','worua99','2018041221.1_48');
Insert into ARMY.CINEMA_RESERVE (CINEMA_NAME,CINEMA_SECTION,CINEMA_MOVIE,CINEMA_MOVIE_TIME,CINEMA_MOVIE_SEAT,MB_ID,CINEMA_RESERVE_NO) values ('kst 목동','임시 상영관','어벤져스','11:50','1_9','worua99','2018041218.1_98');
Insert into ARMY.CINEMA_RESERVE (CINEMA_NAME,CINEMA_SECTION,CINEMA_MOVIE,CINEMA_MOVIE_TIME,CINEMA_MOVIE_SEAT,MB_ID,CINEMA_RESERVE_NO) values ('kst 목동','임시 상영관','어벤져스','11:50','1_10','worua99','2018041218.1_98');
Insert into ARMY.CINEMA_RESERVE (CINEMA_NAME,CINEMA_SECTION,CINEMA_MOVIE,CINEMA_MOVIE_TIME,CINEMA_MOVIE_SEAT,MB_ID,CINEMA_RESERVE_NO) values ('kst 목동','임시 상영관','어벤져스','11:50','3_9','worua99','2018041311.3_95');
Insert into ARMY.CINEMA_RESERVE (CINEMA_NAME,CINEMA_SECTION,CINEMA_MOVIE,CINEMA_MOVIE_TIME,CINEMA_MOVIE_SEAT,MB_ID,CINEMA_RESERVE_NO) values ('kst 목동','임시 상영관','어벤져스','11:50','3_10','worua99','2018041311.3_95');
Insert into ARMY.CINEMA_RESERVE (CINEMA_NAME,CINEMA_SECTION,CINEMA_MOVIE,CINEMA_MOVIE_TIME,CINEMA_MOVIE_SEAT,MB_ID,CINEMA_RESERVE_NO) values ('kst 목동','임시 상영관','어벤져스','11:50','3_11','worua99','2018041311.3_95');
Insert into ARMY.CINEMA_RESERVE (CINEMA_NAME,CINEMA_SECTION,CINEMA_MOVIE,CINEMA_MOVIE_TIME,CINEMA_MOVIE_SEAT,MB_ID,CINEMA_RESERVE_NO) values ('kst 목동','임시 상영관','어벤져스','11:50','3_12','worua99','2018041311.3_95');
Insert into ARMY.CINEMA_RESERVE (CINEMA_NAME,CINEMA_SECTION,CINEMA_MOVIE,CINEMA_MOVIE_TIME,CINEMA_MOVIE_SEAT,MB_ID,CINEMA_RESERVE_NO) values ('kst 목동','임시 상영관','어벤져스','11:50','3_13','worua99','2018041311.3_95');
